version: '3.8'

services:
  terraform-ui:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./sessions:/app/sessions
    environment:
      - FLASK_DEBUG=0
      - CLEANUP_INTERVAL=300
      - INACTIVITY_TIMEOUT=1800